s = float(input())
if((s >= 0)and(s <= 400)):
    b = ((s * 15)/100)
    st = (s+b)
    print('Novo salario: {:.2f}'.format(st))
    print('Reajuste ganho: {:.2f}'.format(b))
    print('Em percentual: 15 %')
elif((s > 400)and(s <= 800)):
    b = ((s * 12)/100)
    st = (s+b)
    print('Novo salario: {:.2f}'.format(st))
    print('Reajuste ganho: {:.2f}'.format(b))
    print('Em percentual: 12 %')
elif((s > 800)and(s <= 1200)):
    b = ((s * 10)/100)
    st = (s+b)
    print('Novo salario: {:.2f}'.format(st))
    print('Reajuste ganho: {:.2f}'.format(b))
    print('Em percentual: 10 %')
elif((s > 1200)and(s <= 2000)):
    b = ((s * 7)/100)
    st = (s+b)
    print('Novo salario: {:.2f}'.format(st))
    print('Reajuste ganho: {:.2f}'.format(b))
    print('Em percentual: 7 %')
elif(s > 2000):
    b = ((s * 4)/100)
    st = (s+b)
    print('Novo salario: {:.2f}'.format(st))
    print('Reajuste ganho: {:.2f}'.format(b))
    print('Em percentual: 4 %')